DROP TABLE IF EXISTS plants_voc, emitters, synonyms;

CREATE TABLE IF NOT EXISTS plants_voc(
    id uuid DEFAULT gen_random_uuid(),
    ipni VARCHAR(50),
    full_name_plain VARCHAR(50),
    full_name_no_authors_plain VARCHAR(50),
    plant_name VARCHAR(30) NOT NULL,
    family VARCHAR(30) NOT NULL,
    genus VARCHAR(30) NOT NULL,
    species VARCHAR(30) NOT NULL,
    valid_nomenclature BOOLEAN,
    rank VARCHAR(20) CHECK (rank IN ('SPECIES','SUBSPECIES','VARIETY','HYBRID','FORM')),
    leaf_habitus VARCHAR(20) CHECK (leaf_habitus IN ('EVERGREEN','DECIDUOUS','SEMI_EVERGREEN','SEMI_DECIDUOUS')),
    created_datetime_utc TIMESTAMP(6) WITH TIME ZONE DEFAULT NOW(),
    updated_datetime_utc TIMESTAMP(6) WITH TIME ZONE DEFAULT NOW(),
    PRIMARY KEY (id)
    );


CREATE TABLE IF NOT EXISTS emitters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    emits BOOLEAN,
    doi VARCHAR(50),
    fk_emitters_plant_id UUID NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS synonyms (
    fk_synonyms_plant_id UUID NOT NULL,
    synonyms VARCHAR(255)
);

ALTER TABLE IF EXISTS emitters
    ADD CONSTRAINT FK_emitters_plant
        FOREIGN KEY (fk_emitters_plant_id)
            REFERENCES plants_voc;


ALTER TABLE IF EXISTS synonyms
    ADD CONSTRAINT FK_synonyms_plant
        FOREIGN KEY (fk_synonyms_plant_id)
            REFERENCES plants_voc